stages:
  feature_eng:
    cmd: python 2-RTN/src/feature_eng.py
    deps:
    - 2-RTN/data/lemmatized/lemmatized.json
    - 2-RTN/src/feature_eng.py
    outs:
    - 2-RTN/data/feature_eng/dataset_fe.csv
