FROM puckel/docker-airflow:1.10.9
ARG NB_USER="airflow"
ARG NB_GID="100"

ENV AIRFLOW_DIR=/usr/local/$NB_USER \
    PROJECT_DIR=/usr/local/rtn-project

USER root
RUN mkdir -p $PROJECT_DIR/data/filtered && mkdir -p $PROJECT_DIR/data/split &&\
    chown $NB_USER:$NB_GID $PROJECT_DIR/data/filtered &&\
    chown $NB_USER:$NB_GID $PROJECT_DIR/data/split

COPY airflow/airflow.cfg $AIRFLOW_DIR/airflow.cfg
COPY data/split $PROJECT_DIR/data/split

COPY ./requirements.txt ./setup.py $PROJECT_DIR/
COPY rtn $PROJECT_DIR/rtn/

RUN pip install $PROJECT_DIR/.
