version: "3.3"

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  scheduler:
    container_name: scheduler
    image: puckel/docker-airflow:1.10.9
    depends_on:
      - postgres
    restart: always
    environment:
      - EXECUTOR=Local
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
#    command: bash -c "airflow initdb && airflow scheduler"
    command: scheduler

  airflow-server:
    container_name: server_container
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_airflow_serv
    depends_on:
      - scheduler
      - postgres
    restart: always
    environment:
      - EXECUTOR=Local
    ports:
      - "8080:8080"
    command:
      - webserver
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3