FROM puckel/docker-airflow:1.10.9

COPY ../airflow/airflow.cfg ${AIRFLOW_HOME}/airflow.cfg

COPY ../data/split ./requirements.txt ./setup.py ./
COPY ../rtn ./rtn/
COPY ../airflow/dags ${AIRFLOW_HOME}/dags

RUN pip install .